# coding: utf-8

"""
    Damacansu Sepeti

    caner bir şeyler yapıyor  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_damacana_damacana_new_post(self):
        """Test case for create_damacana_damacana_new_post

        Create Damacana  # noqa: E501
        """
        pass

    def test_get_damacana_from_id_damacana_id_get(self):
        """Test case for get_damacana_from_id_damacana_id_get

        Get Damacana From Id  # noqa: E501
        """
        pass

    def test_get_damacana_from_name_damacana_search_get(self):
        """Test case for get_damacana_from_name_damacana_search_get

        Get Damacana From Name  # noqa: E501
        """
        pass

    def test_list_damacana_storage_damacana_get(self):
        """Test case for list_damacana_storage_damacana_get

        List Damacana Storage  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
