# coding: utf-8

"""
    Damacansu Sepeti

    caner bir şeyler yapıyor  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_token import UserToken  # noqa: E501
from swagger_client.rest import ApiException


class TestUserToken(unittest.TestCase):
    """UserToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserToken(self):
        """Test UserToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_token.UserToken()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
