# coding: utf-8

"""
    Damacansu Sepeti

    caner bir şeyler yapıyor  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DamacanaDBModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'description': 'str',
        'image': 'str',
        'price': 'float',
        'quantity': 'int'
    }

    attribute_map = {
        'id': '_id',
        'name': 'name',
        'description': 'description',
        'image': 'image',
        'price': 'price',
        'quantity': 'quantity'
    }

    def __init__(self, id=None, name=None, description=None, image=None, price=15.99, quantity=0):  # noqa: E501
        """DamacanaDBModel - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._description = None
        self._image = None
        self._price = None
        self._quantity = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.name = name
        self.description = description
        self.image = image
        if price is not None:
            self.price = price
        if quantity is not None:
            self.quantity = quantity

    @property
    def id(self):
        """Gets the id of this DamacanaDBModel.  # noqa: E501


        :return: The id of this DamacanaDBModel.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DamacanaDBModel.


        :param id: The id of this DamacanaDBModel.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this DamacanaDBModel.  # noqa: E501

        Damacana Name  # noqa: E501

        :return: The name of this DamacanaDBModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DamacanaDBModel.

        Damacana Name  # noqa: E501

        :param name: The name of this DamacanaDBModel.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this DamacanaDBModel.  # noqa: E501

        Damacana Description  # noqa: E501

        :return: The description of this DamacanaDBModel.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this DamacanaDBModel.

        Damacana Description  # noqa: E501

        :param description: The description of this DamacanaDBModel.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def image(self):
        """Gets the image of this DamacanaDBModel.  # noqa: E501

        Damacana Image  # noqa: E501

        :return: The image of this DamacanaDBModel.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this DamacanaDBModel.

        Damacana Image  # noqa: E501

        :param image: The image of this DamacanaDBModel.  # noqa: E501
        :type: str
        """
        if image is None:
            raise ValueError("Invalid value for `image`, must not be `None`")  # noqa: E501

        self._image = image

    @property
    def price(self):
        """Gets the price of this DamacanaDBModel.  # noqa: E501

        Damacana Price  # noqa: E501

        :return: The price of this DamacanaDBModel.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this DamacanaDBModel.

        Damacana Price  # noqa: E501

        :param price: The price of this DamacanaDBModel.  # noqa: E501
        :type: float
        """

        self._price = price

    @property
    def quantity(self):
        """Gets the quantity of this DamacanaDBModel.  # noqa: E501

        Damacana Quantity  # noqa: E501

        :return: The quantity of this DamacanaDBModel.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this DamacanaDBModel.

        Damacana Quantity  # noqa: E501

        :param quantity: The quantity of this DamacanaDBModel.  # noqa: E501
        :type: int
        """

        self._quantity = quantity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DamacanaDBModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DamacanaDBModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
