# coding: utf-8

"""
    Damacansu Sepeti

    caner bir şeyler yapıyor  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserToken(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access_token': 'str',
        'secret_token': 'str',
        'token_type': 'str',
        'expires_in': 'int'
    }

    attribute_map = {
        'access_token': 'access_token',
        'secret_token': 'secret_token',
        'token_type': 'token_type',
        'expires_in': 'expires_in'
    }

    def __init__(self, access_token='', secret_token='', token_type='', expires_in=None):  # noqa: E501
        """UserToken - a model defined in Swagger"""  # noqa: E501
        self._access_token = None
        self._secret_token = None
        self._token_type = None
        self._expires_in = None
        self.discriminator = None
        if access_token is not None:
            self.access_token = access_token
        if secret_token is not None:
            self.secret_token = secret_token
        if token_type is not None:
            self.token_type = token_type
        if expires_in is not None:
            self.expires_in = expires_in

    @property
    def access_token(self):
        """Gets the access_token of this UserToken.  # noqa: E501

        User Access Token  # noqa: E501

        :return: The access_token of this UserToken.  # noqa: E501
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token):
        """Sets the access_token of this UserToken.

        User Access Token  # noqa: E501

        :param access_token: The access_token of this UserToken.  # noqa: E501
        :type: str
        """

        self._access_token = access_token

    @property
    def secret_token(self):
        """Gets the secret_token of this UserToken.  # noqa: E501

        User Secret Token  # noqa: E501

        :return: The secret_token of this UserToken.  # noqa: E501
        :rtype: str
        """
        return self._secret_token

    @secret_token.setter
    def secret_token(self, secret_token):
        """Sets the secret_token of this UserToken.

        User Secret Token  # noqa: E501

        :param secret_token: The secret_token of this UserToken.  # noqa: E501
        :type: str
        """

        self._secret_token = secret_token

    @property
    def token_type(self):
        """Gets the token_type of this UserToken.  # noqa: E501

        Bearer, or whatever.  # noqa: E501

        :return: The token_type of this UserToken.  # noqa: E501
        :rtype: str
        """
        return self._token_type

    @token_type.setter
    def token_type(self, token_type):
        """Sets the token_type of this UserToken.

        Bearer, or whatever.  # noqa: E501

        :param token_type: The token_type of this UserToken.  # noqa: E501
        :type: str
        """

        self._token_type = token_type

    @property
    def expires_in(self):
        """Gets the expires_in of this UserToken.  # noqa: E501

        Token Expires (in minutes)  # noqa: E501

        :return: The expires_in of this UserToken.  # noqa: E501
        :rtype: int
        """
        return self._expires_in

    @expires_in.setter
    def expires_in(self, expires_in):
        """Sets the expires_in of this UserToken.

        Token Expires (in minutes)  # noqa: E501

        :param expires_in: The expires_in of this UserToken.  # noqa: E501
        :type: int
        """

        self._expires_in = expires_in

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserToken, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserToken):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
